# Generated by Django 4.2.5 on 2023-09-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('bank_account', models.CharField(max_length=50)),
                ('role', models.IntegerField(choices=[(0, 'Фрилансер'), (1, 'Заказчик')])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('in_work', models.BooleanField(default=False)),
                ('degree_to_company', models.IntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')])),
                ('degree_to_performer', models.IntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')])),
                ('deadline', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.customer')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take', models.BooleanField(default=False)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.order')),
                ('freelance_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.freelancer')),
            ],
        ),
        migrations.AddField(
            model_name='freelancer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.user'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.user'),
        ),
    ]
