# Generated by Django 4.2.5 on 2023-09-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromwho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_sent', to='freelance_app.user')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.order')),
                ('towho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_received', to='freelance_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.BooleanField()),
                ('summa', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance_app.user')),
            ],
        ),
    ]
