# Generated by Django 4.2.5 on 2023-09-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0002_dealhistory_balanceoperations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealhistory',
            old_name='fromwho',
            new_name='from_who',
        ),
        migrations.RenameField(
            model_name='dealhistory',
            old_name='towho',
            new_name='to_who',
        ),
    ]
