# Generated by Django 4.2.5 on 2023-10-01 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0004_user_about_alter_customer_degree_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserData',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='company',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='degree_to_company',
            field=models.IntegerField(choices=[(0, 'Оценки нет'), (1, 'Очень плохо'), (2, 'Плохо'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='degree_to_performer',
            field=models.IntegerField(choices=[(0, 'Оценки нет'), (1, 'Очень плохо'), (2, 'Плохо'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freelance_app.freelancer'),
        ),
    ]
