# Generated by Django 4.2.5 on 2023-10-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0005_rename_user_userdata_rename_company_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='degree_to_company',
            field=models.IntegerField(blank=True, choices=[(0, 'Оценки нет'), (1, 'Очень плохо'), (2, 'Плохо'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='degree_to_performer',
            field=models.IntegerField(blank=True, choices=[(0, 'Оценки нет'), (1, 'Очень плохо'), (2, 'Плохо'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')], null=True),
        ),
    ]
