# Generated by Django 4.2.5 on 2023-10-03 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelance_app', '0008_alter_order_work_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='django_user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
