# Generated by Django 4.2.5 on 2023-10-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0009_userdata_django_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='password',
        ),
    ]
