# Generated by Django 4.2.1 on 2023-10-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0010_remove_userdata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceoperations',
            name='type_operation',
            field=models.IntegerField(choices=[(0, 'Вывод средств'), (1, 'Пополнение')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_ready',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
