# Generated by Django 4.2.5 on 2023-10-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0010_remove_userdata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceoperations',
            name='type_operation',
            field=models.IntegerField(choices=[(0, 'Вывод средств'), (1, 'Пополнение')]),
        ),
    ]
