# Generated by Django 4.2.5 on 2023-10-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0011_alter_balanceoperations_type_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='work_ready',
            field=models.CharField(blank=True, null=True),
        ),
    ]
