# Generated by Django 4.2.5 on 2023-10-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0012_alter_order_work_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='work_ready',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
